/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is regenerated by `next dev` / `next build`. Do not edit
// it by hand — it is checked in as a placeholder so the skeleton typechecks
// before the first build runs.
