from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
POLICY = ROOT / "scripts" / "contribution_policy.py"
APPROVED = ("Carlo Miguel Dy", "carlomigueldy@gmail.com")
APPROVED_NOREPLY = (
    "Carlo Miguel Dy",
    "45052332+carlomigueldy@users.noreply.github.com",
)
GITHUB = ("GitHub", "noreply@github.com")
BOT = (
    "github-actions[bot]",
    "41898282+github-actions[bot]@users.noreply.github.com",
)


def run(args: list[str], cwd: Path, *, env: dict[str, str] | None = None, check: bool = True):
    merged = os.environ.copy()
    if env:
        merged.update(env)
    return subprocess.run(args, cwd=cwd, env=merged, text=True, capture_output=True, check=check)


def git(repo: Path, *args: str, check: bool = True):
    return run(["git", *args], repo, check=check)


class Repository:
    def __init__(self) -> None:
        # The system /tmp can be mounted noexec; hooks must execute for this smoke test.
        self.temp = tempfile.TemporaryDirectory(dir=ROOT)
        self.path = Path(self.temp.name)
        git(self.path, "init", "-q")
        git(self.path, "config", "user.name", APPROVED[0])
        git(self.path, "config", "user.email", APPROVED[1])

    def close(self) -> None:
        self.temp.cleanup()

    def commit(
        self,
        message: str,
        *,
        author: tuple[str, str] = APPROVED,
        committer: tuple[str, str] | None = None,
        filename: str = "file.txt",
        content: str | bytes | None = None,
    ) -> str:
        target = self.path / filename
        target.parent.mkdir(parents=True, exist_ok=True)
        if content is None:
            content = f"{message}\n"
        if isinstance(content, bytes):
            target.write_bytes(content)
        else:
            target.write_text(content, encoding="utf-8")
        git(self.path, "add", filename)
        committer = committer or author
        env = {
            "GIT_AUTHOR_NAME": author[0],
            "GIT_AUTHOR_EMAIL": author[1],
            "GIT_COMMITTER_NAME": committer[0],
            "GIT_COMMITTER_EMAIL": committer[1],
        }
        run(["git", "commit", "-q", "-m", message], self.path, env=env)
        return git(self.path, "rev-parse", "HEAD").stdout.strip()


class ContributionPolicyTests(unittest.TestCase):
    def setUp(self) -> None:
        self.repo = Repository()

    def tearDown(self) -> None:
        self.repo.close()

    def policy(self, *args: str, check: bool = False, env: dict[str, str] | None = None):
        return run(["python3", str(POLICY), *args], self.repo.path, env=env, check=check)

    def test_message_accepts_headers_scopes_breaking_and_allowlisted_human_coauthor(self):
        for message in (
            "fix: repair validation\n",
            "feat(plugin-core): add mode\n",
            "refactor(api)!: remove legacy field\n",
            "fix: handle failure!\n",
            "fix: parse value?\n",
            "fix: split values;\n",
            f"docs: clarify setup\n\nCo-authored-by: {APPROVED_NOREPLY[0]} <{APPROVED_NOREPLY[1]}>\n",
        ):
            path = self.repo.path / "message"
            path.write_text(message, encoding="utf-8")
            result = self.policy("message", str(path))
            self.assertEqual(result.returncode, 0, result.stderr)

    def test_message_rejects_bad_header_attribution_and_unauthorized_trailers(self):
        invalid = (
            "Update docs\n",
            "feature: update docs\n",
            "fix: \n",
            "fix(UPPER): update docs\n",
            "fix: bypass.\n",
            "docs: generated by Claude\n",
            "docs: update docs\n\nGenerated by Claude\n",
            "docs: update docs\n\nAuthored with **Anthropic Claude**\n",
            "docs: update docs\n\nGenerated by [`Codex`](https://example.invalid)\n",
            f"docs: update docs\n\nSigned-off-by: {APPROVED[0]} <{APPROVED[1]}>\n",
            f"docs: update docs\n\nSigned-off-by : {APPROVED[0]} <{APPROVED[1]}>\n",
            "docs: update docs\n\nCo-authored-by: Claude <bot@example.com>\n",
            "docs: update docs\n\nCo-authored-by : Claude <bot@example.com>\n",
            "docs: update docs\n\nCo-developed-by: Claude\n",
            "docs: update docs\n\nReviewed-by: ChatGPT\n",
            "docs: update docs\n\nBuilt with Claude\n",
            "docs: update docs\n\nGenerated by <strong>Claude</strong>.\n",
            "docs: update docs\n\nGenerated by <!-- hidden -->Claude.\n",
            "docs: update docs\n\nGenerated&nbsp;by Claude.\n",
            "docs: update docs\n\nGenerated by C&#108;aude.\n",
            "docs: update docs\n\nGenerated by C\u217caude.\n",
            "docs: update docs\n\nGenerated by Cl\u200baude.\n",
            "docs: update docs\n\nGenerated by Clau\u2060de.\n",
            "docs: update docs\n\nCode generated by Claude.\n",
            "docs: update docs\n\nMade by Claude.\n",
            "docs: update docs\n\nPair-programmed with Claude.\n",
            "docs: update docs\n\nThanks to Claude for writing this.\n",
            "docs: update docs\n\nClaude wrote this code.\n",
            "docs: update docs\n\nClaude helped write this code.\n",
            "docs: update docs\n\nImplementation credit goes to Codex.\n",
            "docs: update docs\n\nAI assistance was used to write this implementation.\n",
            "docs: update docs\n\nThis patch was written with help from Claude.\n",
            "docs: update docs\n\nCo-authored-by: Other Human <other@example.com>\n",
        )
        for index, message in enumerate(invalid):
            path = self.repo.path / f"bad-{index}"
            path.write_text(message, encoding="utf-8")
            result = self.policy("message", str(path))
            self.assertNotEqual(result.returncode, 0, message)

    def test_technical_model_mentions_are_not_attribution(self):
        path = self.repo.path / "message"
        path.write_text(
            "docs: explain integrations\n\n"
            "Claude and Codex call the OpenAI API; the LLM output is validated.\n"
            "The report is generated using an LLM and validated.\n"
            "Describe content created using OpenAI APIs.\n"
            "Examples generated by GPT-4 are parsed as fixtures.\n"
            "Code generated by GPT-4 is parsed as a fixture.\n",
            encoding="utf-8",
        )
        self.assertEqual(self.policy("message", str(path)).returncode, 0)

    def test_staged_checks_added_text_and_effective_identity(self):
        target = self.repo.path / "notes.md"
        target.write_text("Claude integration documentation\n", encoding="utf-8")
        git(self.repo.path, "add", "notes.md")
        self.assertEqual(self.policy("staged").returncode, 0)

        target.write_text("Claude integration documentation\nGenerated by Codex\n", encoding="utf-8")
        git(self.repo.path, "add", "notes.md")
        self.assertNotEqual(self.policy("staged").returncode, 0)

        target.write_text("Co-developed-by: Claude\n", encoding="utf-8")
        git(self.repo.path, "add", "notes.md")
        self.assertNotEqual(self.policy("staged").returncode, 0)

        target.write_text("safe\n", encoding="utf-8")
        git(self.repo.path, "add", "notes.md")
        bad_env = {
            "GIT_AUTHOR_NAME": "Codex",
            "GIT_AUTHOR_EMAIL": "codex@example.com",
            "GIT_COMMITTER_NAME": APPROVED[0],
            "GIT_COMMITTER_EMAIL": APPROVED[1],
        }
        self.assertNotEqual(self.policy("staged", env=bad_env).returncode, 0)

    def test_range_validates_all_commits_identities_messages_and_transport_committer(self):
        root = self.repo.commit("chore: baseline")
        human = self.repo.commit("feat(core): add feature", committer=GITHUB)
        self.assertEqual(self.policy("range", root, human).returncode, 0)

        bad = self.repo.commit("fix: unsafe", author=("Other", "other@example.com"))
        result = self.policy("range", human, bad)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("author", result.stderr.lower())

        platform_author = self.repo.commit("fix: invalid platform author", author=GITHUB)
        self.assertNotEqual(self.policy("range", bad, platform_author).returncode, 0)

        bad_committer = self.repo.commit(
            "fix: invalid committer",
            author=APPROVED,
            committer=("Other", "other@example.com"),
        )
        self.assertNotEqual(self.policy("range", platform_author, bad_committer).returncode, 0)

        commitlint_only = self.repo.commit("fix: invalid punctuation.")
        self.assertNotEqual(
            self.policy("range", bad_committer, commitlint_only).returncode,
            0,
        )

    def test_release_bot_is_limited_to_release_header_and_transport_committer(self):
        root = self.repo.commit("chore: baseline")
        release = self.repo.commit(
            "chore(main): release product-foundry 1.2.3", author=BOT, committer=GITHUB
        )
        self.assertEqual(self.policy("range", root, release).returncode, 0)
        bad = self.repo.commit("chore: automate", author=BOT, committer=BOT)
        self.assertNotEqual(self.policy("range", release, bad).returncode, 0)

    def test_range_handles_zero_root_binary_rename_delete_and_rejects_non_ancestor(self):
        root = self.repo.commit("chore: baseline", content=b"\x00\xff")
        git(self.repo.path, "mv", "file.txt", "renamed.bin")
        git(self.repo.path, "commit", "-q", "-m", "chore: rename fixture")
        renamed = git(self.repo.path, "rev-parse", "HEAD").stdout.strip()
        git(self.repo.path, "rm", "renamed.bin")
        git(self.repo.path, "commit", "-q", "-m", "chore: delete fixture")
        head = git(self.repo.path, "rev-parse", "HEAD").stdout.strip()
        zeros = "0" * 40
        self.assertEqual(self.policy("range", zeros, head).returncode, 0)
        self.assertEqual(self.policy("range", root, head).returncode, 0)
        self.assertNotEqual(self.policy("range", head, renamed).returncode, 0)

    def test_range_rejects_attribution_added_anywhere_in_range(self):
        root = self.repo.commit("chore: baseline")
        head = self.repo.commit("docs: add credits", content="Written with ChatGPT\n")
        self.assertNotEqual(self.policy("range", root, head).returncode, 0)

    def test_range_rejects_attribution_added_then_deleted_in_later_commit(self):
        root = self.repo.commit("chore: baseline")
        self.repo.commit("docs: add temporary credits", content="Generated by Claude\n")
        head = self.repo.commit("docs: remove temporary credits", content="safe\n")
        self.assertNotEqual(self.policy("range", root, head).returncode, 0)

    def test_range_fails_closed_when_history_is_shallow(self):
        root = self.repo.commit("chore: baseline")
        head = self.repo.commit("fix: next commit")
        git_dir = Path(git(self.repo.path, "rev-parse", "--git-dir").stdout.strip())
        (self.repo.path / git_dir / "shallow").write_text(f"{root}\n", encoding="utf-8")
        result = self.policy("range", root, head)
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("shallow", result.stderr.lower())

    def test_event_validates_pull_request_and_issue_text(self):
        valid = {
            "pull_request": {
                "title": "feat(plugin): add validation",
                "body": "Claude integration behavior is covered.",
                "user": {"login": "carlomigueldy"},
            }
        }
        path = self.repo.path / "event.json"
        path.write_text(json.dumps(valid), encoding="utf-8")
        self.assertEqual(self.policy("event", str(path)).returncode, 0)

        valid["pull_request"]["body"] = "Implemented by Codex"
        path.write_text(json.dumps(valid), encoding="utf-8")
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

        valid["pull_request"]["body"] = "Co-authored-by : Claude <bot@example.com>"
        path.write_text(json.dumps(valid), encoding="utf-8")
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

        valid["pull_request"]["title"] = "feat: authored with Codex"
        valid["pull_request"]["body"] = "safe"
        path.write_text(json.dumps(valid), encoding="utf-8")
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

        path.write_text(
            json.dumps(
                {
                    "issue": {
                        "title": "bug report",
                        "body": "details",
                        "user": {"login": "carlomigueldy"},
                    }
                }
            ),
            encoding="utf-8",
        )
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

        bot_pr = {
            "pull_request": {
                "title": "feat: arbitrary automation",
                "body": "safe",
                "user": {"login": "github-actions[bot]"},
            }
        }
        path.write_text(json.dumps(bot_pr), encoding="utf-8")
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

        bot_pr["pull_request"]["title"] = "chore(main): release product-foundry 1.2.3"
        path.write_text(json.dumps(bot_pr), encoding="utf-8")
        self.assertEqual(self.policy("event", str(path)).returncode, 0)

        path.write_text(
            json.dumps(
                {
                    "pull_request": {
                        "title": "fix: valid",
                        "body": "safe",
                        "user": {"login": "carlomigueldy"},
                    },
                    "issue": {
                        "title": "fix: valid",
                        "body": "safe",
                        "user": {"login": "carlomigueldy"},
                    },
                }
            ),
            encoding="utf-8",
        )
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

        path.write_text(
            json.dumps(
                {
                    "pull_request": {
                        "title": "fix: valid",
                        "body": "safe",
                        "user": {"login": "unapproved-contributor"},
                    }
                }
            ),
            encoding="utf-8",
        )
        self.assertNotEqual(self.policy("event", str(path)).returncode, 0)

    def test_pull_request_workflow_validates_from_the_branch_merge_base(self):
        workflow = (ROOT / ".github/workflows/contribution-policy.yml").read_text(
            encoding="utf-8"
        )
        self.assertIn('git merge-base "$BASE_SHA" "$HEAD_SHA"', workflow)
        self.assertIn('range "$MERGE_BASE" "$HEAD_SHA"', workflow)

    def test_commit_message_hook_preserves_commitlint_failures(self):
        message = self.repo.path / "commit-message"
        message.write_text("fix: Valid.\n", encoding="utf-8")
        result = run(
            ["sh", str(ROOT / ".husky/commit-msg"), str(message)],
            ROOT,
            check=False,
        )
        self.assertNotEqual(result.returncode, 0, result.stderr)

    def test_real_hooks_prevent_invalid_commits(self):
        try:
            subprocess.run(
                [str(ROOT / ".husky" / "pre-commit")],
                cwd=ROOT,
                capture_output=True,
                check=False,
            )
        except PermissionError:
            self.skipTest("workspace sandbox forbids direct hook execution")
        shutil.copytree(ROOT / ".husky", self.repo.path / ".husky")
        for hook in ("pre-commit", "commit-msg"):
            (self.repo.path / ".husky" / hook).chmod(0o755)
        shutil.copy2(POLICY, self.repo.path / "scripts-contribution-policy.py")
        # Hooks resolve the repository script path, matching the installed layout.
        (self.repo.path / "scripts").mkdir()
        shutil.copy2(POLICY, self.repo.path / "scripts" / "contribution_policy.py")
        (self.repo.path / ".github").mkdir()
        shutil.copy2(
            ROOT / ".github" / "contribution-policy.json",
            self.repo.path / ".github" / "contribution-policy.json",
        )
        shutil.copytree(ROOT / "node_modules", self.repo.path / "node_modules", dirs_exist_ok=True)
        shutil.copy2(ROOT / "commitlint.config.cjs", self.repo.path / "commitlint.config.cjs")
        git(self.repo.path, "config", "core.hooksPath", ".husky")

        (self.repo.path / "ok.txt").write_text("safe\n", encoding="utf-8")
        git(self.repo.path, "add", "ok.txt")
        valid = git(self.repo.path, "commit", "-m", "test: valid hook", check=False)
        self.assertEqual(valid.returncode, 0, valid.stderr)

        baseline = git(self.repo.path, "rev-parse", "HEAD").stdout.strip()
        cases = (
            ("bad-title.txt", "safe\n", ["-m", "bad title"], None),
            ("credit.txt", "Generated by Claude\n", ["-m", "test: reject credit"], None),
            (
                "trailer.txt",
                "safe\n",
                ["-m", "test: reject trailer", "-m", "Co-authored-by: Claude <bot@example.com>"],
                None,
            ),
            (
                "identity.txt",
                "safe\n",
                ["-m", "test: reject identity override"],
                {
                    "GIT_AUTHOR_NAME": "Codex",
                    "GIT_AUTHOR_EMAIL": "codex@example.com",
                    "GIT_COMMITTER_NAME": APPROVED[0],
                    "GIT_COMMITTER_EMAIL": APPROVED[1],
                },
            ),
        )
        for filename, content, commit_args, env in cases:
            (self.repo.path / filename).write_text(content, encoding="utf-8")
            git(self.repo.path, "add", filename)
            result = run(["git", "commit", *commit_args], self.repo.path, env=env, check=False)
            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(git(self.repo.path, "rev-parse", "HEAD").stdout.strip(), baseline)
            git(self.repo.path, "restore", "--staged", filename)


if __name__ == "__main__":
    unittest.main()
