#!/usr/bin/env python3
"""Regenerate the top-level skills/ mirror from one or more plugins' skills/.

Codex CLI, OpenCode, and the cross-agent installer (`npx skills add
carlomigueldy/skills`) don't know anything about Claude plugin layout -- they
scan a repo's top-level `skills/` directory. The canonical skills live under
each mirrored plugin's `plugins/<name>/skills/` (that's what the Claude
plugin loads), so this script keeps a generated copy at the repo root in
sync with them.

Two things it handles:

1. **Regeneration.** Build a fresh copy of every `MIRRORED_PLUGINS` source
   into a staging directory, then swap it in for `skills/`, and drop a
   `.generated` marker so nobody mistakes the mirror for a place to make
   edits.

2. **Drift checking (`--check`).** Build the would-be mirror in a temp
   directory and diff it against the committed `skills/`, without touching
   anything on disk. Meant for CI: exits 0 when they match, 1 with a concise
   list of drifted paths otherwise.

Usage:
    scripts/sync-skills.py            # regenerate skills/ in place
    scripts/sync-skills.py --check    # verify skills/ is up to date (CI)
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent

# Explicit opt-in, not manifest-driven discovery: an unrecognized key in a
# plugin's plugin.json is a gamble against `claude plugin validate`, which
# CI runs. Add a plugin here only once its skills/ is ready to ship in the
# flat mirror.
MIRRORED_PLUGINS = ("orchestra", "saas-launch")

MARKER_NAME = ".generated"

# Never mirror these, regardless of what's on disk.
EXCLUDED_FILES = {".DS_Store"}


class MirrorError(Exception):
    """Raised when the mirror cannot be safely built (e.g. a name collision)."""


def should_skip(name: str) -> bool:
    return name in EXCLUDED_FILES


def source_dirs(repo_root: Path) -> list[tuple[str, Path]]:
    """(relative_posix, absolute) pairs for every mirrored plugin's skills/.

    Sorted so the marker and any collision message are deterministic
    regardless of `MIRRORED_PLUGINS` order.
    """
    return sorted(
        (f"plugins/{name}/skills", repo_root / "plugins" / name / "skills")
        for name in MIRRORED_PLUGINS
    )


def marker_content(sources: Iterable[str]) -> str:
    """The `.generated` marker body for the given (sorted) source labels.

    With a single source this is byte-identical to the marker this script
    has always written -- that backward-compat guarantee is what lets a
    validator written against the legacy single-source marker keep parsing
    it once this script mirrors more than one plugin.
    """
    joined = ", ".join(sources)
    return (
        f"generated by scripts/sync-skills.py from {joined} "
        "-- edit the source, not this mirror.\n"
    )


def build_mirror(dest: Path, sources: list[tuple[str, Path]]) -> dict[str, str]:
    """Populate `dest` from `sources` plus the marker file.

    Returns a map of top-level entry name -> owning source (relative
    posix), which `diff_dirs` uses to attribute drift to the plugin that
    owns it.

    Raises `MirrorError` if a source directory is missing, or if two
    sources ship a top-level entry whose names collide case-insensitively
    -- the repo already treats case-only differences as real path
    collisions (see `validate_plugins._validate_package_paths`'s
    `collision_key = archive_path.casefold()`), so the mirror does too.
    """
    dest.mkdir(parents=True, exist_ok=True)
    owners: dict[str, str] = {}
    seen_casefold: dict[str, str] = {}
    for source_relative, source_path in sources:
        if not source_path.is_dir():
            raise MirrorError(f"source dir {source_path} does not exist.")
        for entry in sorted(source_path.iterdir()):
            if should_skip(entry.name):
                continue
            key = entry.name.casefold()
            if key in seen_casefold:
                prev_name = seen_casefold[key]
                prev_source = owners[prev_name]
                raise MirrorError(
                    f"name collision: {prev_source} entry {prev_name!r} and "
                    f"{source_relative} entry {entry.name!r} both mirror to "
                    f"the same top-level skills/ path"
                )
            seen_casefold[key] = entry.name
            owners[entry.name] = source_relative
            target = dest / entry.name
            if entry.is_dir():
                shutil.copytree(
                    entry,
                    target,
                    ignore=shutil.ignore_patterns(*EXCLUDED_FILES),
                )
            else:
                shutil.copy2(entry, target)

    (dest / MARKER_NAME).write_text(
        marker_content(source for source, _ in sources), encoding="utf-8"
    )
    return owners


def iter_relative_files(root: Path) -> set[str]:
    """All file paths under `root`, relative and POSIX-formatted."""
    if not root.is_dir():
        return set()
    return {
        p.relative_to(root).as_posix()
        for p in root.rglob("*")
        if p.is_file() and not should_skip(p.name)
    }


def diff_dirs(expected: Path, actual: Path, owners: dict[str, str]) -> list[str]:
    """Return a sorted list of concise drift descriptions, empty if equal.

    `missing:`/`changed:` lines are attributed to the owning source via
    `owners`; `unexpected:` lines get no attribution -- an unexpected file
    belongs to nobody's source.
    """
    problems: list[str] = []

    expected_files = iter_relative_files(expected)
    actual_files = iter_relative_files(actual)

    missing = sorted(expected_files - actual_files)
    extra = sorted(actual_files - expected_files)
    common = sorted(expected_files & actual_files)

    def attribution(relative: str) -> str:
        top_level = relative.split("/", 1)[0]
        source = owners.get(top_level)
        return f" (from {source})" if source else ""

    problems += [f"missing: {rel}{attribution(rel)}" for rel in missing]
    problems += [f"unexpected: {rel}" for rel in extra]

    for rel in common:
        if not filecmp.cmp(expected / rel, actual / rel, shallow=False):
            problems.append(f"changed: {rel}{attribution(rel)}")

    return problems


def run_check(mirror_dir: Path, sources: list[tuple[str, Path]]) -> int:
    joined = ", ".join(name for name, _ in sources)

    if not mirror_dir.is_dir():
        print(f"error: {mirror_dir} does not exist -- mirror has not been generated yet.")
        print("Run scripts/sync-skills.py to generate it.")
        return 1

    with tempfile.TemporaryDirectory(prefix="sync-skills-") as tmp:
        expected = Path(tmp) / "skills"
        owners = build_mirror(expected, sources)
        problems = diff_dirs(expected, mirror_dir, owners)

    if not problems:
        print(f"OK: {mirror_dir} matches {joined}.")
        return 0

    print(f"error: {mirror_dir} is out of date with {joined}:")
    for problem in problems:
        print(f"  {problem}")
    print("\nRun scripts/sync-skills.py to regenerate the mirror.")
    return 1


def run_sync(mirror_dir: Path, sources: list[tuple[str, Path]]) -> int:
    """Stage a fresh mirror in a tempdir, then swap it in.

    Building in a tempdir first (rather than the old rmtree-then-build
    order) means a failure partway through -- including a name collision
    -- leaves the committed `skills/` untouched instead of deleted.
    `shutil.move` (not `Path.rename`) so the tempdir-to-repo swap works
    even when they're on different filesystems.
    """
    with tempfile.TemporaryDirectory(prefix="sync-skills-build-") as tmp:
        staged = Path(tmp) / "skills"
        build_mirror(staged, sources)
        if mirror_dir.exists():
            shutil.rmtree(mirror_dir)
        shutil.move(str(staged), str(mirror_dir))

    file_count = len(iter_relative_files(mirror_dir))
    joined = ", ".join(name for name, _ in sources)
    print(f"Regenerated {mirror_dir} from {joined} ({file_count} files).")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate or check the top-level skills/ mirror.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify skills/ matches the source without writing anything (CI)",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    mirror_dir = repo_root / "skills"
    sources = source_dirs(repo_root)

    try:
        exit_code = (
            run_check(mirror_dir, sources)
            if args.check
            else run_sync(mirror_dir, sources)
        )
    except MirrorError as exc:
        sys.exit(f"error: {exc}")
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
