#!/usr/bin/env python3
"""Regenerate the top-level skills/ mirror from plugins/saas-launch/skills/.

Codex CLI, OpenCode, and the cross-agent installer (`npx skills add
carlomigueldy/skills`) don't know anything about Claude plugin layout -- they
scan a repo's top-level `skills/` directory. The canonical skills live under
`plugins/saas-launch/skills/` (that's what the Claude plugin loads), so this
script keeps a generated copy at the repo root in sync with them.

Two things it handles:

1. **Regeneration.** Delete `skills/` entirely and recopy it from
   `plugins/saas-launch/skills/*`, then drop a `.generated` marker so nobody
   mistakes the mirror for a place to make edits.

2. **Drift checking (`--check`).** Build the would-be mirror in a temp
   directory and diff it against the committed `skills/`, without touching
   anything on disk. Meant for CI: exits 0 when they match, 1 with a concise
   list of drifted paths otherwise.

Usage:
    scripts/sync-skills.py            # regenerate skills/ in place
    scripts/sync-skills.py --check    # verify skills/ is up to date (CI)
"""

from __future__ import annotations

import argparse
import filecmp
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = REPO_ROOT / "plugins" / "saas-launch" / "skills"
MIRROR_DIR = REPO_ROOT / "skills"

MARKER_NAME = ".generated"
MARKER_CONTENT = (
    "generated by scripts/sync-skills.py from plugins/saas-launch/skills "
    "-- edit the source, not this mirror.\n"
)

# Never mirror these, regardless of what's on disk.
EXCLUDED_FILES = {".DS_Store"}


def should_skip(name: str) -> bool:
    return name in EXCLUDED_FILES


def build_mirror(dest: Path) -> None:
    """Populate `dest` with a fresh copy of SOURCE_DIR plus the marker file."""
    if not SOURCE_DIR.is_dir():
        sys.exit(f"error: source dir {SOURCE_DIR} does not exist.")

    dest.mkdir(parents=True, exist_ok=True)
    for entry in sorted(SOURCE_DIR.iterdir()):
        if should_skip(entry.name):
            continue
        target = dest / entry.name
        if entry.is_dir():
            shutil.copytree(
                entry,
                target,
                ignore=shutil.ignore_patterns(*EXCLUDED_FILES),
            )
        else:
            shutil.copy2(entry, target)

    (dest / MARKER_NAME).write_text(MARKER_CONTENT, encoding="utf-8")


def iter_relative_files(root: Path) -> set[str]:
    """All file paths under `root`, relative and POSIX-formatted."""
    if not root.is_dir():
        return set()
    return {
        p.relative_to(root).as_posix()
        for p in root.rglob("*")
        if p.is_file() and not should_skip(p.name)
    }


def diff_dirs(expected: Path, actual: Path) -> list[str]:
    """Return a sorted list of concise drift descriptions, empty if equal."""
    problems: list[str] = []

    expected_files = iter_relative_files(expected)
    actual_files = iter_relative_files(actual)

    missing = sorted(expected_files - actual_files)
    extra = sorted(actual_files - expected_files)
    common = sorted(expected_files & actual_files)

    problems += [f"missing: {rel}" for rel in missing]
    problems += [f"unexpected: {rel}" for rel in extra]

    for rel in common:
        if not filecmp.cmp(expected / rel, actual / rel, shallow=False):
            problems.append(f"changed: {rel}")

    return problems


def run_check() -> int:
    if not MIRROR_DIR.is_dir():
        print(f"error: {MIRROR_DIR} does not exist -- mirror has not been generated yet.")
        print("Run scripts/sync-skills.py to generate it.")
        return 1

    with tempfile.TemporaryDirectory(prefix="sync-skills-") as tmp:
        expected = Path(tmp) / "skills"
        build_mirror(expected)
        problems = diff_dirs(expected, MIRROR_DIR)

    if not problems:
        print(f"OK: {MIRROR_DIR} matches plugins/saas-launch/skills/.")
        return 0

    print(f"error: {MIRROR_DIR} is out of date with plugins/saas-launch/skills/:")
    for problem in problems:
        print(f"  {problem}")
    print("\nRun scripts/sync-skills.py to regenerate the mirror.")
    return 1


def run_sync() -> int:
    if MIRROR_DIR.exists():
        shutil.rmtree(MIRROR_DIR)
    build_mirror(MIRROR_DIR)
    file_count = len(iter_relative_files(MIRROR_DIR))
    print(f"Regenerated {MIRROR_DIR} from plugins/saas-launch/skills/ ({file_count} files).")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate or check the top-level skills/ mirror.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify skills/ matches the source without writing anything (CI)",
    )
    args = parser.parse_args()

    sys.exit(run_check() if args.check else run_sync())


if __name__ == "__main__":
    main()
