#!/usr/bin/env python3
"""Validate every discovered plugin and its repository registrations."""

from __future__ import annotations

import argparse
import filecmp
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]

# `package_exclusions` is a sibling module, not a `scripts.` package import:
# this script is also invoked directly (`python3 scripts/validate_plugins.py`),
# where only its own directory is on sys.path, not the repo root. Ensuring
# that directory is present makes the import work identically whether this
# runs standalone or gets imported as `scripts.validate_plugins` by a test.
_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))
from package_exclusions import EXCLUDED_DIRS  # noqa: E402

SEMVER = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)"
    r"(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?"
    r"(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$"
)
MIRROR_MARKER = re.compile(
    r"^generated by scripts/sync-skills\.py from "
    r"(plugins/[a-z0-9][a-z0-9-]*/skills"
    r"(?:, plugins/[a-z0-9][a-z0-9-]*/skills)*) "
)
MIRROR_SOURCE = re.compile(r"plugins/([a-z0-9][a-z0-9-]*)/skills")
MARKETPLACE_NAME = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
# Mirrors sync-skills.py's EXCLUDED_FILES. Kept as a separate constant (not
# imported) because the hyphenated script filename isn't import-able by name.
MIRROR_EXCLUDED_FILES = {".DS_Store"}

# __pycache__ is pruned from the walk in `_validate_package_paths` rather
# than flagged here: it is regenerated automatically the moment any plugin
# ships importable Python, and CI runs `unittest discover` (which imports
# it) immediately before this validator -- flagging it would fail every run
# through no fault of the committed tree, and package-plugin.py would never
# have shipped it anyway. The rest of EXCLUDED_DIRS is never an unavoidable
# side effect of this repo's own tooling, so those stay flagged below: their
# presence is a real signal something was built or installed somewhere it
# shouldn't have been, not a false positive.
UNSAFE_PARTS = EXCLUDED_DIRS - {"__pycache__"}
ARCHIVE_ILLEGAL = re.compile(r'[<>:"|?*\\\[\]]|[^\x20-\x7e]')
WINDOWS_DEVICES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{index}" for index in range(1, 10)),
    *(f"LPT{index}" for index in range(1, 10)),
}
GENERATED_RESTORE_FILES = {"restore-paths.md", "restore-paths.sh"}
# Explicit mapping, not filename-derived discovery: discovery fails open (delete
# the validator script and validation silently passes) whereas a plugin listed
# here with a missing script must error loudly instead.
FOCUSED_VALIDATORS = {
    "herdcraft": "scripts/validate_herdcraft.py",
    "orchestra": "scripts/validate_orchestra.py",
    "product-foundry": "scripts/validate_product_foundry.py",
}

# pi has no subdirectory selector for git sources -- it clones the whole repo
# and treats the repo root as the package root -- so one root manifest is the
# only thing that routes `pi install git:...` at the per-plugin skill trees
# instead of the generated mirror. Exposing the mirror as well would collide
# all 25 mirrored skill names (pi keeps the first and warns on the rest) and
# would hand pi the copies whose ../../references links resolve to nothing.
PI_MANIFEST_FILE = "package.json"
PI_RESOURCE_TYPES = ("extensions", "skills", "prompts", "themes")
PI_OVERRIDE_PREFIXES = ("!", "+", "-")
PI_GLOB_CHARACTERS = frozenset("*?[]")


def _sanitize_archive_path(relative: str) -> str:
    parts: list[str] = []
    for part in relative.split("/"):
        bracketed = re.fullmatch(r"\[(.+)\]", part)
        parts.append(
            f"__{bracketed.group(1)}__"
            if bracketed
            else ARCHIVE_ILLEGAL.sub("_", part)
        )
    return "/".join(parts)


def _read_json(path: Path, errors: list[str]) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        errors.append(f"missing JSON file: {path}")
    except (OSError, UnicodeError) as exc:
        errors.append(f"cannot read JSON file {path}: {exc}")
    except json.JSONDecodeError as exc:
        errors.append(f"invalid JSON in {path}: {exc.msg} (line {exc.lineno})")
    return None


def discover_plugins(root: Path) -> list[Path]:
    """Return package directories discovered directly below plugins/."""
    plugins_dir = root / "plugins"
    if not plugins_dir.is_dir():
        return []
    return sorted(
        (path for path in plugins_dir.iterdir() if path.is_dir()),
        key=lambda path: path.name,
    )


def _extra_file_paths(config: dict[str, Any]) -> set[str]:
    extra_files = config.get("extra-files", [])
    if not isinstance(extra_files, list):
        return set()
    return {
        item["path"]
        for item in extra_files
        if isinstance(item, dict) and isinstance(item.get("path"), str)
    }


def _validate_package_paths(package: Path, errors: list[str]) -> None:
    if package.is_symlink():
        errors.append(f"{package.name}: plugin package directory must not be a symlink")
    package_resolved = package.resolve()
    archive_paths: dict[str, str] = {}
    needs_restore = False
    root_files: set[str] = set()
    for current, dirs, files in os.walk(package, followlinks=False):
        # Never descend into __pycache__: nothing under it is ever packaged
        # (package-plugin.py prunes it too), so nothing under it should be
        # checked either -- see the UNSAFE_PARTS comment above.
        dirs[:] = sorted(d for d in dirs if d != "__pycache__")
        current_path = Path(current)
        for name in sorted([*dirs, *files]):
            path = current_path / name
            relative = path.relative_to(package)
            if any(part in UNSAFE_PARTS for part in relative.parts):
                errors.append(f"{package.name}: unsafe packaged path: {relative}")
            if any(ord(char) < 32 or char == "\\" for char in relative.as_posix()):
                errors.append(f"{package.name}: unsafe packaged path: {relative}")
            for segment in relative.parts:
                device_stem = segment.rstrip(" .").split(".", 1)[0].upper()
                if segment.endswith((" ", ".")) or device_stem in WINDOWS_DEVICES:
                    errors.append(
                        f"{package.name}: Windows-unsafe packaged path: {relative}"
                    )
                    break
            if path.is_symlink():
                try:
                    path.resolve(strict=True).relative_to(package_resolved)
                except (FileNotFoundError, RuntimeError, ValueError):
                    errors.append(
                        f"{package.name}: unsafe packaged symlink escapes package: {relative}"
                    )
        for name in sorted(files):
            relative = (current_path / name).relative_to(package).as_posix()
            archive_path = _sanitize_archive_path(relative)
            needs_restore = needs_restore or archive_path != relative
            if "/" not in relative:
                root_files.add(relative.casefold())
            collision_key = archive_path.casefold()
            previous = archive_paths.get(collision_key)
            if previous is not None and previous != relative:
                errors.append(
                    f"{package.name}: archive path collision after sanitization: "
                    f"{previous} and {relative} -> {archive_path}"
                )
            else:
                archive_paths[collision_key] = relative
    if needs_restore:
        for generated_name in sorted(GENERATED_RESTORE_FILES & root_files):
            errors.append(
                f"{package.name}: source shadows generated restore file: {generated_name}"
            )


def _validate_skills(
    package: Path,
    codex_manifest: dict[str, Any] | None,
    errors: list[str],
) -> None:
    skills_root = package / "skills"
    if not skills_root.is_dir():
        errors.append(f"{package.name}: missing required skills/ directory")
        return

    # pi's mode-aware skill discovery promotes any top-level `*.md` file
    # directly under a scanned skills root to a skill in its own right, not
    # just `*/SKILL.md` directories -- so a stray root-level Markdown file
    # here becomes an unreviewed 41st skill for pi installs even though
    # every other host and this validator's own skill enumeration ignore
    # it. Reject non-directory children outright rather than silently
    # skipping them.
    #
    # `.DS_Store` is the one exception, tolerated here for the same reason
    # it is tolerated in the mirror checks below: macOS creates it in any
    # browsed directory, it is gitignored, and pi never promotes it to a
    # skill (only top-level `*.md` files are promoted). Failing on it would
    # break local validation on a maintainer's machine for a file that is
    # neither committed nor loadable.
    for entry in sorted(skills_root.iterdir()):
        if entry.name in MIRROR_EXCLUDED_FILES:
            continue
        if not entry.is_dir():
            errors.append(
                f"{package.name}: skills/ must contain only skill directories: "
                f"{entry.name}"
            )
    skill_dirs = sorted(path for path in skills_root.iterdir() if path.is_dir())
    if not skill_dirs:
        errors.append(f"{package.name}: skills/ contains no skill entrypoints")
    frontmatter_names: list[str] = []
    for skill_dir in skill_dirs:
        entrypoint = skill_dir / "SKILL.md"
        if not entrypoint.is_file():
            errors.append(
                f"{package.name}: missing required skill entrypoint: "
                f"skills/{skill_dir.name}/SKILL.md"
            )
            continue
        try:
            header = entrypoint.read_text(encoding="utf-8")[:4096]
        except (OSError, UnicodeError) as exc:
            errors.append(f"{entrypoint}: cannot read skill entrypoint: {exc}")
            continue
        match = re.search(r"(?m)^name:\s*['\"]?([^'\"\n]+)", header)
        if not match:
            errors.append(f"{entrypoint}: missing skill frontmatter name")
            continue
        skill_name = match.group(1).strip()
        frontmatter_names.append(skill_name)
        if skill_name != skill_dir.name:
            errors.append(
                f"{entrypoint}: skill name {skill_name!r} must match directory "
                f"{skill_dir.name!r}"
            )
    duplicates = sorted(
        name for name, count in Counter(frontmatter_names).items() if count > 1
    )
    for name in duplicates:
        errors.append(f"{package.name}: duplicate skill name: {name}")

    if codex_manifest is not None:
        reference = codex_manifest.get("skills")
        if not isinstance(reference, str) or not reference:
            errors.append(f"{package.name}: Codex manifest needs a skills path")
        else:
            candidate = package / reference
            try:
                candidate.resolve(strict=True).relative_to(package.resolve())
            except (FileNotFoundError, RuntimeError, ValueError):
                errors.append(
                    f"{package.name}: Codex skills path is unsafe or missing: {reference}"
                )
            else:
                if candidate.resolve() != skills_root.resolve():
                    errors.append(
                        f"{package.name}: Codex skills path must resolve to ./skills/: "
                        f"{reference}"
                    )


def _canonical_mirror_marker(sources: Iterable[str]) -> str:
    """The exact `.generated` text sync-skills.py's `marker_content` writes
    for these (already-sorted) sources.

    Duplicated here rather than imported -- the hyphenated script filename
    isn't import-able by name -- so a marker that merely starts with a
    recognizable prefix but was hand-edited or corrupted afterward (e.g. a
    stripped or altered trailing warning) fails a byte-exact comparison
    instead of sailing through on a prefix-only regex match.
    """
    joined = ", ".join(sources)
    return (
        f"generated by scripts/sync-skills.py from {joined} "
        "-- edit the source, not this mirror.\n"
    )


def _validate_mirror(root: Path, selected: set[str], errors: list[str]) -> None:
    mirror = root / "skills"
    marker = mirror / ".generated"
    if not marker.is_file():
        return
    try:
        marker_text = marker.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        errors.append(f"generated skills mirror marker cannot be read: {exc}")
        return

    match = MIRROR_MARKER.match(marker_text)
    if not match:
        errors.append("generated skills mirror has an unrecognized .generated marker")
        return

    sources_relative = match.group(1).split(", ")
    plugin_names: list[str] = []
    for source_relative in sources_relative:
        source_match = MIRROR_SOURCE.fullmatch(source_relative)
        if source_match is None:
            errors.append(
                "generated skills mirror has an unrecognized .generated marker"
            )
            return
        plugin_names.append(source_match.group(1))

    # A marker sync-skills.py would actually write always lists sources
    # sorted and comma-joined with nothing else on the line. Either
    # deviation means the marker is not trustworthy -- fail loudly rather
    # than silently skipping the drift check below with these sources.
    if sources_relative != sorted(sources_relative):
        errors.append("generated skills mirror marker sources are not sorted")
        return
    if marker_text != _canonical_mirror_marker(sources_relative):
        errors.append("generated skills mirror has an unrecognized .generated marker")
        return

    if not set(plugin_names) & selected:
        return

    missing_sources = sorted(
        source_relative
        for source_relative in sources_relative
        if not (root / source_relative).is_dir()
    )
    for source_relative in missing_sources:
        errors.append(f"generated skills mirror source is missing: {source_relative}")
    if missing_sources:
        return

    # Casefolded collision detection across every named source's top-level
    # entries, replicating sync-skills.py's build_mirror() rule (see
    # _validate_package_paths's own `collision_key = archive_path.casefold()`
    # for the same rationale elsewhere in this file). The validator can't
    # simply trust that the committed marker was produced by a collision-free
    # build -- the underlying plugin skills/ directories may have drifted
    # since the marker was last regenerated.
    owners: dict[str, str] = {}
    seen_casefold: dict[str, str] = {}
    collision = False
    for source_relative in sources_relative:
        source = root / source_relative
        for entry in sorted(source.iterdir()):
            if entry.name in MIRROR_EXCLUDED_FILES:
                continue
            key = entry.name.casefold()
            if key in seen_casefold:
                prev_name = seen_casefold[key]
                prev_source = owners[prev_name]
                errors.append(
                    "generated skills mirror sources collide: "
                    f"{prev_source} entry {prev_name!r} and "
                    f"{source_relative} entry {entry.name!r} both mirror to "
                    "the same top-level skills/ path"
                )
                collision = True
                continue
            seen_casefold[key] = entry.name
            owners[entry.name] = source_relative
    if collision:
        return

    source_files: dict[str, Path] = {}
    for source_relative in sources_relative:
        source = root / source_relative
        for path in source.rglob("*"):
            if path.is_file() and path.name not in MIRROR_EXCLUDED_FILES:
                source_files[path.relative_to(source).as_posix()] = path
    mirror_files = {
        path.relative_to(mirror).as_posix(): path
        for path in mirror.rglob("*")
        if path.is_file() and path.name != ".generated"
    }
    missing = sorted(source_files.keys() - mirror_files.keys())
    extra = sorted(mirror_files.keys() - source_files.keys())
    changed = sorted(
        relative
        for relative in source_files.keys() & mirror_files.keys()
        if not filecmp.cmp(source_files[relative], mirror_files[relative], shallow=False)
    )

    def attribution(relative: str) -> str:
        top_level = relative.split("/", 1)[0]
        source = owners.get(top_level)
        return f" (from {source})" if source else ""

    for relative in missing:
        errors.append(
            f"generated skills mirror is missing: {relative}{attribution(relative)}"
        )
    for relative in extra:
        errors.append(f"generated skills mirror has an unexpected file: {relative}")
    for relative in changed:
        errors.append(
            f"generated skills mirror has drifted: {relative}{attribution(relative)}"
        )


def validate_pi_manifest(root: Path, discovered: set[str], errors: list[str]) -> None:
    """Validate the repository-root pi package manifest.

    Public (not `_`-prefixed) because both `main` (the `--pi-manifest-only`
    CLI path) and the tests call it directly, mirroring how
    `validate_orchestra.validate_codex_manifest` is exposed. `discovered`
    must be every plugin under `plugins/`, not whatever `--plugin` narrowed
    a run to -- this manifest is a repository-level registry, and its
    correctness never depends on which plugin the caller happened to ask
    about.
    """
    payload = _read_json(root / PI_MANIFEST_FILE, errors)
    if payload is None:
        # _read_json already appended a specific, actionable message
        # (missing file / unreadable / bad JSON); piling a second, vaguer
        # message on top of it would only obscure the real cause.
        return
    if not isinstance(payload, dict):
        errors.append("root package.json must be a JSON object")
        return

    # pi's git-install path always runs `npm install --omit=dev` against
    # the cloned repo -- `--ignore-scripts` appears nowhere in pi's dist/ --
    # so an unguarded `prepare` script still executes without
    # devDependencies on `PATH`. If that script assumes a devDependency
    # binary exists (husky does), it exits non-zero, pi's install throws
    # before persisting the source to settings, and the user is left with
    # an unremovable half-cloned package on disk. `|| true` is the whole
    # fix; this just keeps it from regressing silently.
    scripts = payload.get("scripts")
    if isinstance(scripts, dict):
        prepare = scripts.get("prepare")
        if isinstance(prepare, str) and "||" not in prepare:
            errors.append(
                "root package.json prepare script must tolerate failure: pi "
                "runs `npm install --omit=dev` on git installs, which still "
                "executes prepare without devDependencies"
            )

    keywords = payload.get("keywords")
    if not isinstance(keywords, list) or "pi-package" not in keywords:
        errors.append('root package.json keywords must include "pi-package"')

    pi_manifest = payload.get("pi")
    if not isinstance(pi_manifest, dict):
        errors.append("root package.json must declare a pi manifest object")
        return

    skills = pi_manifest.get("skills")
    if (
        not isinstance(skills, list)
        or not skills
        or not all(isinstance(entry, str) and entry for entry in skills)
    ):
        errors.append("pi manifest skills must be a non-empty list of strings")
        return

    # Each entry is checked against these rules in order, first failure
    # wins and the entry contributes nothing further -- this mirrors how
    # pi itself would treat the same string (an override pattern is
    # stripped from the source list before resolution ever runs; a glob or
    # an escaping path is not something this repo's flat `plugins/*/skills`
    # layout should ever need).
    resolved: set[str] = set()
    for entry in skills:
        if entry.startswith(PI_OVERRIDE_PREFIXES):
            errors.append(
                "pi manifest skills entry is an override pattern and "
                f"contributes no skills: {entry}"
            )
            continue
        if any(character in PI_GLOB_CHARACTERS for character in entry):
            errors.append(f"pi manifest skills entry must not be a glob: {entry}")
            continue
        if Path(entry).is_absolute() or ".." in Path(entry).parts:
            errors.append(
                f"pi manifest skills entry must stay inside the repository: {entry}"
            )
            continue
        if not (root / entry).is_dir():
            errors.append(
                f"pi manifest skills entry does not resolve to a directory: {entry}"
            )
            continue
        resolved.add(entry.rstrip("/"))

    # Set equality, not a one-directional subset check: a plugin missing
    # from `pi.skills` fails *silently* for every pi user (no error, no
    # warning -- the skills simply don't exist for them, same as
    # product-foundry doesn't exist for mirror-based installs today), so
    # "added a plugin, forgot pi" has to be a hard failure here.
    # Codex-only plugins are intentionally absent from pi: a native Codex
    # manifest is not permission to expose the package to another host.
    # Existing cross-host plugins all carry a Claude manifest, which remains
    # the repository's signal that their skill tree belongs in the pi bundle.
    expected = {
        f"plugins/{name}/skills"
        for name in discovered
        if (root / "plugins" / name / ".claude-plugin/plugin.json").is_file()
    }
    for missing in sorted(expected - resolved):
        errors.append(f"pi manifest must expose {missing}")
    for extra in sorted(resolved - expected):
        if extra == "skills":
            errors.append(
                "pi manifest must not expose the generated skills/ mirror: it "
                "duplicates every mirrored skill name and its cross-package "
                "references do not resolve"
            )
        else:
            errors.append(f"pi manifest exposes an unexpected skills root: {extra}")

    # A *partial* pi key is worse than a missing one: pi's manifest reader
    # only falls back to convention discovery when the whole `pi` key is
    # absent, so declaring `skills` here silently disables convention
    # discovery for every *other* resource type the moment a root
    # `extensions/`, `prompts/`, or `themes/` directory shows up -- with no
    # error from pi itself, since an omitted key just means "load nothing"
    # to pi's `addManifestEntries`.
    for resource in PI_RESOURCE_TYPES:
        if resource == "skills":
            continue
        if (root / resource).is_dir() and resource not in pi_manifest:
            errors.append(
                f"pi manifest declares skills but not {resource}: a partial "
                "pi manifest disables convention discovery for every omitted "
                "resource type"
            )

    # Per-plugin package.json is banned outright, not just discouraged:
    # convention discovery already serves the local-path install case it
    # would exist for, so the only effect of adding one is a fourth version
    # file per plugin that release-please must keep in lockstep with the
    # other three -- see the spec's decision (b).
    for name in sorted(discovered):
        if (root / "plugins" / name / PI_MANIFEST_FILE).exists():
            errors.append(
                f"{name}: plugins must not carry their own package.json; pi "
                "discovers a plugin package by convention and a per-plugin "
                "package.json adds a fourth version to keep in lockstep"
            )


def _run_focused_validator(root: Path, plugin_name: str, errors: list[str]) -> None:
    relative = FOCUSED_VALIDATORS.get(plugin_name)
    if relative is None:
        return
    validator = root / relative
    if not validator.is_file():
        errors.append(f"{plugin_name}: missing focused validator")
        return
    try:
        result = subprocess.run(
            [sys.executable, str(validator), str(root)],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
            timeout=120,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        errors.append(f"{plugin_name}: focused validator could not run: {exc}")
        return
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        errors.append(
            f"{plugin_name}: focused validator failed"
            + (f": {detail}" if detail else "")
        )


def _validate_registries(
    root: Path,
    selected: set[str],
    discovered: set[str],
    check_orphans: bool,
    errors: list[str],
) -> tuple[dict[str, Any], dict[str, Any]]:
    marketplace = _read_json(root / ".claude-plugin/marketplace.json", errors)
    codex_marketplace_path = root / ".agents/plugins/marketplace.json"
    codex_marketplace = (
        _read_json(codex_marketplace_path, errors)
        if codex_marketplace_path.exists()
        else {}
    )
    release_config = _read_json(root / "release-please-config.json", errors)
    release_manifest = _read_json(root / ".release-please-manifest.json", errors)
    marketplace = marketplace if isinstance(marketplace, dict) else {}
    codex_marketplace = (
        codex_marketplace if isinstance(codex_marketplace, dict) else {}
    )
    release_config = release_config if isinstance(release_config, dict) else {}
    release_manifest = release_manifest if isinstance(release_manifest, dict) else {}

    entries = marketplace.get("plugins", [])
    if not isinstance(entries, list):
        errors.append("marketplace plugins must be a list")
        entries = []
    valid_entries = [entry for entry in entries if isinstance(entry, dict)]
    if len(valid_entries) != len(entries):
        errors.append("marketplace plugin entries must be objects")
    entry_names = [
        entry.get("name")
        for entry in valid_entries
        if isinstance(entry.get("name"), str)
    ]
    entry_sources = [
        entry.get("source")
        for entry in valid_entries
        if isinstance(entry.get("source"), str)
    ]
    for name, count in Counter(entry_names).items():
        if count > 1:
            errors.append(f"marketplace has duplicate plugin name: {name}")
    for source, count in Counter(entry_sources).items():
        if count > 1:
            errors.append(f"marketplace has duplicate plugin source: {source}")
    for entry in valid_entries:
        name = entry.get("name")
        source = entry.get("source")
        if not isinstance(name, str) or not isinstance(source, str):
            errors.append("marketplace plugin entries require string name and source")
            continue
        expected = f"./plugins/{name}"
        if source != expected:
            errors.append(
                f"marketplace entry {name!r} must use safe source {expected!r}"
            )

    if codex_marketplace_path.exists():
        codex_name = codex_marketplace.get("name")
        if not isinstance(codex_name, str) or not MARKETPLACE_NAME.fullmatch(
            codex_name
        ):
            errors.append(
                "Codex marketplace name must use lowercase letters, digits, dots, "
                "underscores, or hyphens"
            )
        codex_interface = codex_marketplace.get("interface")
        if not isinstance(codex_interface, dict):
            errors.append("Codex marketplace interface must be an object")
        elif not isinstance(
            codex_interface.get("displayName"), str
        ) or not codex_interface["displayName"].strip():
            errors.append("Codex marketplace interface.displayName must be non-empty")

    codex_entries = codex_marketplace.get("plugins", [])
    if not isinstance(codex_entries, list):
        errors.append("Codex marketplace plugins must be a list")
        codex_entries = []
    valid_codex_entries = [entry for entry in codex_entries if isinstance(entry, dict)]
    if len(valid_codex_entries) != len(codex_entries):
        errors.append("Codex marketplace plugin entries must be objects")
    codex_entry_names: list[str] = []
    codex_entry_paths: list[str] = []
    for entry in valid_codex_entries:
        name = entry.get("name")
        source = entry.get("source")
        source_path = source.get("path") if isinstance(source, dict) else None
        if not isinstance(name, str) or not isinstance(source_path, str):
            errors.append(
                "Codex marketplace plugin entries require string name and local source.path"
            )
            continue
        codex_entry_names.append(name)
        codex_entry_paths.append(source_path)
        expected = f"./plugins/{name}"
        if source.get("source") != "local" or source_path != expected:
            errors.append(
                f"Codex marketplace entry {name!r} must use local source {expected!r}"
            )
        policy = entry.get("policy")
        if not isinstance(policy, dict) or policy.get("installation") not in {
            "NOT_AVAILABLE",
            "AVAILABLE",
            "INSTALLED_BY_DEFAULT",
        } or policy.get("authentication") not in {"ON_INSTALL", "ON_USE"}:
            errors.append(f"Codex marketplace entry {name!r} has invalid policy")
        if not isinstance(entry.get("category"), str):
            errors.append(f"Codex marketplace entry {name!r} requires category")
    for name, count in Counter(codex_entry_names).items():
        if count > 1:
            errors.append(f"Codex marketplace has duplicate plugin name: {name}")
    for source, count in Counter(codex_entry_paths).items():
        if count > 1:
            errors.append(f"Codex marketplace has duplicate plugin source: {source}")

    packages = release_config.get("packages", {})
    if not isinstance(packages, dict):
        errors.append("release-please packages must be an object")
        packages = {}
    if check_orphans:
        for name in sorted(set(entry_names) - discovered):
            errors.append(f"{name}: orphan marketplace registration")
        for name in sorted(set(codex_entry_names) - discovered):
            errors.append(f"{name}: orphan Codex marketplace registration")
        registered_packages = {
            key.removeprefix("plugins/")
            for key in packages
            if isinstance(key, str) and key.startswith("plugins/")
        }
        for name in sorted(registered_packages - discovered):
            errors.append(f"{name}: orphan release-please package registration")
        manifest_packages = {
            key.removeprefix("plugins/")
            for key in release_manifest
            if isinstance(key, str) and key.startswith("plugins/")
        }
        for name in sorted(manifest_packages - discovered):
            errors.append(f"{name}: orphan release-please manifest entry")
    for plugin_name in selected:
        expected_source = f"./plugins/{plugin_name}"
        matching = [
            entry
            for entry in valid_entries
            if entry.get("name") == plugin_name
            and entry.get("source") == expected_source
        ]
        has_claude_manifest = (
            root / "plugins" / plugin_name / ".claude-plugin/plugin.json"
        ).is_file()
        has_codex_manifest = (
            root / "plugins" / plugin_name / ".codex-plugin/plugin.json"
        ).is_file()
        codex_matching = [
            entry
            for entry in valid_codex_entries
            if entry.get("name") == plugin_name
            and isinstance(entry.get("source"), dict)
            and entry["source"].get("source") == "local"
            and entry["source"].get("path") == expected_source
        ]
        if has_claude_manifest and len(matching) != 1:
            errors.append(
                f"{plugin_name}: marketplace must register exactly one matching entry"
            )
        elif not has_claude_manifest and matching:
            errors.append(
                f"{plugin_name}: Claude marketplace must not register a plugin without a Claude manifest"
            )
        if has_codex_manifest and len(codex_matching) != 1:
            errors.append(
                f"{plugin_name}: Codex marketplace must register exactly one matching entry"
            )
        elif not has_codex_manifest and codex_matching:
            errors.append(
                f"{plugin_name}: Codex marketplace must not register a plugin without a Codex manifest"
            )
        if not has_claude_manifest and not has_codex_manifest:
            errors.append(f"{plugin_name}: missing supported plugin manifest")
        package_key = f"plugins/{plugin_name}"
        if not isinstance(packages.get(package_key), dict):
            errors.append(f"{plugin_name}: missing release-please package registration")
        if package_key not in release_manifest:
            errors.append(f"{plugin_name}: missing release-please manifest entry")
    return packages, release_manifest


def validate_repository(
    root: Path,
    *,
    plugin_names: Iterable[str] | None = None,
) -> list[str]:
    """Validate repository plugin contracts and return all discovered errors."""
    root = Path(root).resolve()
    errors: list[str] = []
    discovered_paths = discover_plugins(root)
    discovered = {path.name: path for path in discovered_paths}
    if not discovered:
        errors.append(f"no plugins discovered under {root / 'plugins'}")
        return errors

    requested = list(plugin_names) if plugin_names is not None else sorted(discovered)
    unknown = sorted(set(requested) - discovered.keys())
    for name in unknown:
        available = ", ".join(sorted(discovered))
        errors.append(f"unknown plugin {name!r}; discovered: {available}")
    selected = set(requested) & discovered.keys()

    release_packages, release_manifest = _validate_registries(
        root,
        selected,
        set(discovered),
        plugin_names is None,
        errors,
    )
    manifest_names: list[str] = []
    for plugin_name in sorted(selected):
        package = discovered[plugin_name]
        _validate_package_paths(package, errors)
        claude_path = package / ".claude-plugin/plugin.json"
        codex_path = package / ".codex-plugin/plugin.json"
        claude: dict[str, Any] | None = None
        codex: dict[str, Any] | None = None
        if claude_path.exists():
            loaded = _read_json(claude_path, errors)
            claude = loaded if isinstance(loaded, dict) else {}
        if codex_path.exists():
            loaded = _read_json(codex_path, errors)
            codex = loaded if isinstance(loaded, dict) else {}
        primary = claude if claude is not None else codex
        if primary is None:
            primary = {}
        name = primary.get("name")
        if isinstance(name, str):
            manifest_names.append(name)
        if name != plugin_name:
            errors.append(f"{plugin_name}: manifest name must be {plugin_name!r}")
        version = primary.get("version")
        if not isinstance(version, str) or not SEMVER.fullmatch(version):
            errors.append(f"{plugin_name}: manifest version must be semantic")

        if claude is not None and codex is not None:
            if codex.get("name") != claude.get("name"):
                errors.append(f"{plugin_name}: Claude and Codex names must match")
            if codex.get("version") != claude.get("version"):
                errors.append(f"{plugin_name}: Claude and Codex versions must match")

        version_path = package / "version.txt"
        try:
            text_version = version_path.read_text(encoding="utf-8").strip()
        except (OSError, UnicodeError):
            errors.append(f"{plugin_name}: missing or unreadable version.txt")
            text_version = None
        if isinstance(version, str) and text_version != version:
            errors.append(f"{plugin_name}: version.txt must match plugin manifest")

        release_key = f"plugins/{plugin_name}"
        release = release_packages.get(release_key)
        if isinstance(release, dict):
            if release.get("release-type") != "simple":
                errors.append(f"{plugin_name}: release type must be simple")
            extra_paths = _extra_file_paths(release)
            required_manifests = set()
            if claude_path.exists():
                required_manifests.add(".claude-plugin/plugin.json")
            if codex_path.exists():
                required_manifests.add(".codex-plugin/plugin.json")
            for relative in sorted(required_manifests - extra_paths):
                errors.append(
                    f"{plugin_name}: release-please must synchronize {relative}"
                )
        released_version = release_manifest.get(release_key)
        if isinstance(version, str) and released_version != version:
            errors.append(
                f"{plugin_name}: release manifest version must match plugin version"
            )

        _validate_skills(package, codex, errors)
        _run_focused_validator(root, plugin_name, errors)

    for name, count in Counter(manifest_names).items():
        if count > 1:
            errors.append(f"duplicate plugin manifest name: {name}")
    _validate_mirror(root, selected, errors)
    validate_pi_manifest(root, set(discovered), errors)
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate discovered plugin packages and repository registrations."
    )
    parser.add_argument(
        "--plugin",
        action="append",
        dest="plugins",
        metavar="NAME",
        help="validate only this discovered plugin (repeatable)",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--pi-manifest-only",
        action="store_true",
        help="validate only the repository-root pi package manifest",
    )
    args = parser.parse_args(argv)
    if args.pi_manifest_only:
        if args.plugins:
            parser.error("--pi-manifest-only cannot be combined with --plugin")
        root = args.repo_root.resolve()
        errors: list[str] = []
        discovered = {path.name for path in discover_plugins(root)}
        if not discovered:
            errors.append(f"no plugins discovered under {root / 'plugins'}")
        else:
            validate_pi_manifest(root, discovered, errors)
        if errors:
            print("pi manifest validation failed:", file=sys.stderr)
            print("\n".join(f"- {error}" for error in errors), file=sys.stderr)
            return 1
        print(f"pi manifest validation passed: {root}")
        return 0
    errors = validate_repository(args.repo_root, plugin_names=args.plugins)
    if errors:
        print("Plugin validation failed:", file=sys.stderr)
        print("\n".join(f"- {error}" for error in errors), file=sys.stderr)
        return 1
    selected = ", ".join(args.plugins) if args.plugins else "all discovered plugins"
    print(f"Plugin validation passed for {selected}: {args.repo_root.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
