#!/usr/bin/env python3
"""Validate every discovered plugin and its repository registrations."""

from __future__ import annotations

import argparse
import filecmp
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
SEMVER = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)"
    r"(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?"
    r"(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$"
)
MIRROR_MARKER = re.compile(
    r"^generated by scripts/sync-skills\.py from "
    r"(plugins/([a-z0-9][a-z0-9-]*)/skills) "
)
UNSAFE_PARTS = {
    ".git",
    ".next",
    ".turbo",
    "__pycache__",
    "dist",
    "node_modules",
}
ARCHIVE_ILLEGAL = re.compile(r'[<>:"|?*\\\[\]]|[^\x20-\x7e]')
WINDOWS_DEVICES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{index}" for index in range(1, 10)),
    *(f"LPT{index}" for index in range(1, 10)),
}
GENERATED_RESTORE_FILES = {"restore-paths.md", "restore-paths.sh"}


def _sanitize_archive_path(relative: str) -> str:
    parts: list[str] = []
    for part in relative.split("/"):
        bracketed = re.fullmatch(r"\[(.+)\]", part)
        parts.append(
            f"__{bracketed.group(1)}__"
            if bracketed
            else ARCHIVE_ILLEGAL.sub("_", part)
        )
    return "/".join(parts)


def _read_json(path: Path, errors: list[str]) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        errors.append(f"missing JSON file: {path}")
    except (OSError, UnicodeError) as exc:
        errors.append(f"cannot read JSON file {path}: {exc}")
    except json.JSONDecodeError as exc:
        errors.append(f"invalid JSON in {path}: {exc.msg} (line {exc.lineno})")
    return None


def discover_plugins(root: Path) -> list[Path]:
    """Return package directories discovered directly below plugins/."""
    plugins_dir = root / "plugins"
    if not plugins_dir.is_dir():
        return []
    return sorted(
        (path for path in plugins_dir.iterdir() if path.is_dir()),
        key=lambda path: path.name,
    )


def _extra_file_paths(config: dict[str, Any]) -> set[str]:
    extra_files = config.get("extra-files", [])
    if not isinstance(extra_files, list):
        return set()
    return {
        item["path"]
        for item in extra_files
        if isinstance(item, dict) and isinstance(item.get("path"), str)
    }


def _validate_package_paths(package: Path, errors: list[str]) -> None:
    if package.is_symlink():
        errors.append(f"{package.name}: plugin package directory must not be a symlink")
    package_resolved = package.resolve()
    archive_paths: dict[str, str] = {}
    needs_restore = False
    root_files: set[str] = set()
    for current, dirs, files in os.walk(package, followlinks=False):
        current_path = Path(current)
        for name in sorted([*dirs, *files]):
            path = current_path / name
            relative = path.relative_to(package)
            if any(part in UNSAFE_PARTS for part in relative.parts):
                errors.append(f"{package.name}: unsafe packaged path: {relative}")
            if any(ord(char) < 32 or char == "\\" for char in relative.as_posix()):
                errors.append(f"{package.name}: unsafe packaged path: {relative}")
            for segment in relative.parts:
                device_stem = segment.rstrip(" .").split(".", 1)[0].upper()
                if segment.endswith((" ", ".")) or device_stem in WINDOWS_DEVICES:
                    errors.append(
                        f"{package.name}: Windows-unsafe packaged path: {relative}"
                    )
                    break
            if path.is_symlink():
                try:
                    path.resolve(strict=True).relative_to(package_resolved)
                except (FileNotFoundError, RuntimeError, ValueError):
                    errors.append(
                        f"{package.name}: unsafe packaged symlink escapes package: {relative}"
                    )
        for name in sorted(files):
            relative = (current_path / name).relative_to(package).as_posix()
            archive_path = _sanitize_archive_path(relative)
            needs_restore = needs_restore or archive_path != relative
            if "/" not in relative:
                root_files.add(relative.casefold())
            collision_key = archive_path.casefold()
            previous = archive_paths.get(collision_key)
            if previous is not None and previous != relative:
                errors.append(
                    f"{package.name}: archive path collision after sanitization: "
                    f"{previous} and {relative} -> {archive_path}"
                )
            else:
                archive_paths[collision_key] = relative
    if needs_restore:
        for generated_name in sorted(GENERATED_RESTORE_FILES & root_files):
            errors.append(
                f"{package.name}: source shadows generated restore file: {generated_name}"
            )


def _validate_skills(
    package: Path,
    codex_manifest: dict[str, Any] | None,
    errors: list[str],
) -> None:
    skills_root = package / "skills"
    if not skills_root.is_dir():
        errors.append(f"{package.name}: missing required skills/ directory")
        return

    skill_dirs = sorted(path for path in skills_root.iterdir() if path.is_dir())
    if not skill_dirs:
        errors.append(f"{package.name}: skills/ contains no skill entrypoints")
    frontmatter_names: list[str] = []
    for skill_dir in skill_dirs:
        entrypoint = skill_dir / "SKILL.md"
        if not entrypoint.is_file():
            errors.append(
                f"{package.name}: missing required skill entrypoint: "
                f"skills/{skill_dir.name}/SKILL.md"
            )
            continue
        try:
            header = entrypoint.read_text(encoding="utf-8")[:4096]
        except (OSError, UnicodeError) as exc:
            errors.append(f"{entrypoint}: cannot read skill entrypoint: {exc}")
            continue
        match = re.search(r"(?m)^name:\s*['\"]?([^'\"\n]+)", header)
        if not match:
            errors.append(f"{entrypoint}: missing skill frontmatter name")
            continue
        skill_name = match.group(1).strip()
        frontmatter_names.append(skill_name)
        if skill_name != skill_dir.name:
            errors.append(
                f"{entrypoint}: skill name {skill_name!r} must match directory "
                f"{skill_dir.name!r}"
            )
    duplicates = sorted(
        name for name, count in Counter(frontmatter_names).items() if count > 1
    )
    for name in duplicates:
        errors.append(f"{package.name}: duplicate skill name: {name}")

    if codex_manifest is not None:
        reference = codex_manifest.get("skills")
        if not isinstance(reference, str) or not reference:
            errors.append(f"{package.name}: Codex manifest needs a skills path")
        else:
            candidate = package / reference
            try:
                candidate.resolve(strict=True).relative_to(package.resolve())
            except (FileNotFoundError, RuntimeError, ValueError):
                errors.append(
                    f"{package.name}: Codex skills path is unsafe or missing: {reference}"
                )
            else:
                if candidate.resolve() != skills_root.resolve():
                    errors.append(
                        f"{package.name}: Codex skills path must resolve to ./skills/: "
                        f"{reference}"
                    )


def _validate_mirror(root: Path, selected: set[str], errors: list[str]) -> None:
    mirror = root / "skills"
    marker = mirror / ".generated"
    if not marker.is_file():
        return
    try:
        marker_text = marker.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        errors.append(f"generated skills mirror marker cannot be read: {exc}")
        return
    match = MIRROR_MARKER.match(marker_text)
    if not match:
        errors.append("generated skills mirror has an unrecognized .generated marker")
        return
    source_relative, plugin_name = match.groups()
    if plugin_name not in selected:
        return
    source = root / source_relative
    if not source.is_dir():
        errors.append(f"generated skills mirror source is missing: {source_relative}")
        return

    source_files = {
        path.relative_to(source).as_posix(): path
        for path in source.rglob("*")
        if path.is_file()
    }
    mirror_files = {
        path.relative_to(mirror).as_posix(): path
        for path in mirror.rglob("*")
        if path.is_file() and path.name != ".generated"
    }
    missing = sorted(source_files.keys() - mirror_files.keys())
    extra = sorted(mirror_files.keys() - source_files.keys())
    changed = sorted(
        relative
        for relative in source_files.keys() & mirror_files.keys()
        if not filecmp.cmp(source_files[relative], mirror_files[relative], shallow=False)
    )
    for relative in missing:
        errors.append(f"generated skills mirror is missing: {relative}")
    for relative in extra:
        errors.append(f"generated skills mirror has an unexpected file: {relative}")
    for relative in changed:
        errors.append(f"generated skills mirror has drifted: {relative}")


def _run_focused_validator(root: Path, plugin_name: str, errors: list[str]) -> None:
    if plugin_name != "product-foundry":
        return
    validator = root / "scripts" / "validate_product_foundry.py"
    if not validator.is_file():
        errors.append("product-foundry: missing focused validator")
        return
    try:
        result = subprocess.run(
            [sys.executable, str(validator), str(root)],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
            timeout=120,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        errors.append(f"product-foundry: focused validator could not run: {exc}")
        return
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        errors.append(
            "product-foundry: focused validator failed"
            + (f": {detail}" if detail else "")
        )


def _validate_registries(
    root: Path,
    selected: set[str],
    discovered: set[str],
    check_orphans: bool,
    errors: list[str],
) -> tuple[dict[str, Any], dict[str, Any]]:
    marketplace = _read_json(root / ".claude-plugin/marketplace.json", errors)
    release_config = _read_json(root / "release-please-config.json", errors)
    release_manifest = _read_json(root / ".release-please-manifest.json", errors)
    marketplace = marketplace if isinstance(marketplace, dict) else {}
    release_config = release_config if isinstance(release_config, dict) else {}
    release_manifest = release_manifest if isinstance(release_manifest, dict) else {}

    entries = marketplace.get("plugins", [])
    if not isinstance(entries, list):
        errors.append("marketplace plugins must be a list")
        entries = []
    valid_entries = [entry for entry in entries if isinstance(entry, dict)]
    if len(valid_entries) != len(entries):
        errors.append("marketplace plugin entries must be objects")
    entry_names = [
        entry.get("name")
        for entry in valid_entries
        if isinstance(entry.get("name"), str)
    ]
    entry_sources = [
        entry.get("source")
        for entry in valid_entries
        if isinstance(entry.get("source"), str)
    ]
    for name, count in Counter(entry_names).items():
        if count > 1:
            errors.append(f"marketplace has duplicate plugin name: {name}")
    for source, count in Counter(entry_sources).items():
        if count > 1:
            errors.append(f"marketplace has duplicate plugin source: {source}")
    for entry in valid_entries:
        name = entry.get("name")
        source = entry.get("source")
        if not isinstance(name, str) or not isinstance(source, str):
            errors.append("marketplace plugin entries require string name and source")
            continue
        expected = f"./plugins/{name}"
        if source != expected:
            errors.append(
                f"marketplace entry {name!r} must use safe source {expected!r}"
            )

    packages = release_config.get("packages", {})
    if not isinstance(packages, dict):
        errors.append("release-please packages must be an object")
        packages = {}
    if check_orphans:
        for name in sorted(set(entry_names) - discovered):
            errors.append(f"{name}: orphan marketplace registration")
        registered_packages = {
            key.removeprefix("plugins/")
            for key in packages
            if isinstance(key, str) and key.startswith("plugins/")
        }
        for name in sorted(registered_packages - discovered):
            errors.append(f"{name}: orphan release-please package registration")
        manifest_packages = {
            key.removeprefix("plugins/")
            for key in release_manifest
            if isinstance(key, str) and key.startswith("plugins/")
        }
        for name in sorted(manifest_packages - discovered):
            errors.append(f"{name}: orphan release-please manifest entry")
    for plugin_name in selected:
        expected_source = f"./plugins/{plugin_name}"
        matching = [
            entry
            for entry in valid_entries
            if entry.get("name") == plugin_name
            and entry.get("source") == expected_source
        ]
        if len(matching) != 1:
            errors.append(
                f"{plugin_name}: marketplace must register exactly one matching entry"
            )
        package_key = f"plugins/{plugin_name}"
        if not isinstance(packages.get(package_key), dict):
            errors.append(f"{plugin_name}: missing release-please package registration")
        if package_key not in release_manifest:
            errors.append(f"{plugin_name}: missing release-please manifest entry")
    return packages, release_manifest


def validate_repository(
    root: Path,
    *,
    plugin_names: Iterable[str] | None = None,
) -> list[str]:
    """Validate repository plugin contracts and return all discovered errors."""
    root = Path(root).resolve()
    errors: list[str] = []
    discovered_paths = discover_plugins(root)
    discovered = {path.name: path for path in discovered_paths}
    if not discovered:
        errors.append(f"no plugins discovered under {root / 'plugins'}")
        return errors

    requested = list(plugin_names) if plugin_names is not None else sorted(discovered)
    unknown = sorted(set(requested) - discovered.keys())
    for name in unknown:
        available = ", ".join(sorted(discovered))
        errors.append(f"unknown plugin {name!r}; discovered: {available}")
    selected = set(requested) & discovered.keys()

    release_packages, release_manifest = _validate_registries(
        root,
        selected,
        set(discovered),
        plugin_names is None,
        errors,
    )
    manifest_names: list[str] = []
    for plugin_name in sorted(selected):
        package = discovered[plugin_name]
        _validate_package_paths(package, errors)
        claude_path = package / ".claude-plugin/plugin.json"
        claude = _read_json(claude_path, errors)
        if not isinstance(claude, dict):
            claude = {}
        name = claude.get("name")
        if isinstance(name, str):
            manifest_names.append(name)
        if name != plugin_name:
            errors.append(
                f"{plugin_name}: Claude manifest name must be {plugin_name!r}"
            )
        version = claude.get("version")
        if not isinstance(version, str) or not SEMVER.fullmatch(version):
            errors.append(f"{plugin_name}: Claude manifest version must be semantic")

        codex_path = package / ".codex-plugin/plugin.json"
        codex: dict[str, Any] | None = None
        if codex_path.exists():
            loaded = _read_json(codex_path, errors)
            codex = loaded if isinstance(loaded, dict) else {}
            if codex.get("name") != name:
                errors.append(f"{plugin_name}: Claude and Codex names must match")
            if codex.get("version") != version:
                errors.append(f"{plugin_name}: Claude and Codex versions must match")

        version_path = package / "version.txt"
        try:
            text_version = version_path.read_text(encoding="utf-8").strip()
        except (OSError, UnicodeError):
            errors.append(f"{plugin_name}: missing or unreadable version.txt")
            text_version = None
        if isinstance(version, str) and text_version != version:
            errors.append(f"{plugin_name}: version.txt must match Claude manifest")

        release_key = f"plugins/{plugin_name}"
        release = release_packages.get(release_key)
        if isinstance(release, dict):
            if release.get("release-type") != "simple":
                errors.append(f"{plugin_name}: release type must be simple")
            extra_paths = _extra_file_paths(release)
            required_manifests = {".claude-plugin/plugin.json"}
            if codex_path.exists():
                required_manifests.add(".codex-plugin/plugin.json")
            for relative in sorted(required_manifests - extra_paths):
                errors.append(
                    f"{plugin_name}: release-please must synchronize {relative}"
                )
        released_version = release_manifest.get(release_key)
        if isinstance(version, str) and released_version != version:
            errors.append(
                f"{plugin_name}: release manifest version must match plugin version"
            )

        _validate_skills(package, codex, errors)
        _run_focused_validator(root, plugin_name, errors)

    for name, count in Counter(manifest_names).items():
        if count > 1:
            errors.append(f"duplicate plugin manifest name: {name}")
    _validate_mirror(root, selected, errors)
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate discovered plugin packages and repository registrations."
    )
    parser.add_argument(
        "--plugin",
        action="append",
        dest="plugins",
        metavar="NAME",
        help="validate only this discovered plugin (repeatable)",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args(argv)
    errors = validate_repository(args.repo_root, plugin_names=args.plugins)
    if errors:
        print("Plugin validation failed:", file=sys.stderr)
        print("\n".join(f"- {error}" for error in errors), file=sys.stderr)
        return 1
    selected = ", ".join(args.plugins) if args.plugins else "all discovered plugins"
    print(f"Plugin validation passed for {selected}: {args.repo_root.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
