import * as Sentry from "@sentry/react";
import { QueryClient } from "@tanstack/react-query";
import { PersistQueryClientProvider, type Persister } from "@tanstack/react-query-persist-client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { del, get, set } from "idb-keyval";
import posthog from "posthog-js";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import "./index.css";
import "./lib/i18n";

// Generated by @tanstack/router-plugin (see vite.config.ts) from the
// file-based routes in ./routes on every `pnpm dev` / `pnpm build`. This
// file does not exist until the plugin has run at least once — that's
// expected, not a bug; do not hand-write it.
import { routeTree } from "./routeTree.gen";

Sentry.init({
  dsn: import.meta.env.VITE_SENTRY_DSN,
  enabled: Boolean(import.meta.env.VITE_SENTRY_DSN) && import.meta.env.PROD,
  environment: import.meta.env.MODE,
  tracesSampleRate: 0.1,
});

if (import.meta.env.VITE_POSTHOG_KEY) {
  posthog.init(import.meta.env.VITE_POSTHOG_KEY, {
    api_host: import.meta.env.VITE_POSTHOG_HOST ?? "https://us.i.posthog.com",
    person_profiles: "identified_only",
  });
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 60_000,
      gcTime: 24 * 60 * 60 * 1000, // keep cached reads around for a day of offline browsing
      retry: 2,
    },
  },
});

// IndexedDB-backed persister for TanStack Query, keyed per product so
// multiple {{PRODUCT_SLUG}} environments (dev/staging) sharing a browser
// profile don't clobber each other's cache.
const IDB_QUERY_CACHE_KEY = "{{PRODUCT_SLUG}}-query-cache";

const idbPersister: Persister = {
  persistClient: async (client) => {
    await set(IDB_QUERY_CACHE_KEY, client);
  },
  restoreClient: async () => get(IDB_QUERY_CACHE_KEY),
  removeClient: async () => {
    await del(IDB_QUERY_CACHE_KEY);
  },
};

const router = createRouter({ routeTree });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const rootElement = document.getElementById("root");
if (!rootElement) throw new Error("Root element #root not found");

createRoot(rootElement).render(
  <StrictMode>
    <PersistQueryClientProvider
      client={queryClient}
      persistOptions={{ persister: idbPersister, maxAge: 24 * 60 * 60 * 1000 }}
    >
      <RouterProvider router={router} />
    </PersistQueryClientProvider>
  </StrictMode>,
);
